"""Risky keyword weights used by the scam detector.

Weights: 3 = high risk, 2 = medium risk, 1 = low risk.
Keywords cover English, Hindi (Devanagari), and Gujarati.
"""

RISKY_KEYWORDS: dict[str, int] = {
    # ── English ──────────────────────────────────────────────────────────────
    # Credentials / identity (high)
    "otp": 3, "one time password": 3, "one-time password": 3,
    "one time code": 3, "one-time code": 3, "pin": 3, "atm pin": 3,
    "upi pin": 3, "cvv": 3, "atm cvv": 3, "password": 3, "passcode": 3,
    "ssn": 3, "social security number": 3, "aadhar": 3, "aadhaar": 3,
    "identity number": 3, "security code": 3, "auth code": 3,
    "authentication code": 3, "share otp": 3, "share password": 3,
    "share pin": 3, "one time password.": 3,
    # Verification / account (medium)
    "verify now": 2, "verify account": 2, "verify your account": 2,
    "verify phone number": 2, "confirm": 2, "confirm identity": 2,
    "confirm now": 2, "account verification": 2, "verification": 1,
    "bank": 2, "bank account": 2, "account number": 2, "account": 2,
    "suspend account": 2, "suspended account": 2,
    "secure your account": 2, "secure your account now": 2,
    "secure": 1, "security": 1, "security alert": 2,
    "transaction": 2, "transaction alert": 2, "unauthorized transaction": 2,
    "transaction failed": 2, "payment": 2, "payment due": 2,
    "confirm payment": 2, "refund": 2, "refund pending": 2, "chargeback": 2,
    "transfer": 2, "fund transfer": 2, "immediate transfer": 2,
    "transfer now": 2, "credit": 2, "debit": 2, "credit card": 2,
    "debit card": 2, "banking": 2, "bank notice": 2,
    "lottery": 2, "lottery winner": 2, "winner": 2, "win": 1, "prize": 2,
    "claim": 2, "claim prize": 2, "redeem": 2, "redeem reward": 2,
    "reward": 2, "giveaway": 2, "giveaway contest": 2, "reward points": 2,
    "suspend": 2, "suspended": 2, "alert": 2, "fraud": 2, "fraud alert": 2,
    "phishing": 2, "phishing scam": 2, "scam": 2, "scammer": 2,
    "scamming": 2, "hacking": 2, "hacked": 2, "hacker": 2, "hack": 2,
    "urgent": 2, "urgent action": 2, "urgent update": 2,
    "urgent update required": 2, "immediately": 2,
    "immediate action required": 2, "immediate action needed": 2,
    "act now": 1, "act quickly": 1, "final notice": 1,
    "final notice sent": 1, "last chance": 1, "last chance offer": 1,
    "dont miss": 1, "don't miss": 1, "limited": 1, "limited time": 1,
    "limited time offer": 1, "exclusive": 1, "important": 1,
    "attention": 1, "offer": 1, "free": 1, "free offer": 1,
    "risk-free": 1, "guarantee": 1, "trial": 1,
    "click": 1, "click here": 1, "click the link": 1, "click link": 1,
    "link": 1, "shortlink": 1, "bit.ly": 1, "tinyurl": 1, "short url": 1,
    "download": 1, "attachment": 1, "open attachment": 1,
    "subscribe": 1, "subscribe now": 1, "bonus": 1, "cash": 1, "money": 1,
    "transfer money": 2, "gift": 1, "gift card": 1, "cash prize": 1,
    "win cash": 1, "important update": 1, "alert message": 1,
    "customer support": 1, "customer care": 1, "helpdesk": 1,
    "call back": 1, "call us now": 1, "contact us": 1,
    "verify details": 2, "update information": 2,
    "update your information": 2, "provide details": 2,
    "submit documents": 2, "send documents": 2, "do not share": 1,
    "suspicious activity": 1, "suspicious": 1, "suspicious transaction": 2,
    "warning": 1, "caution": 1, "danger": 1, "notice": 1,
    "final warning": 1, "authorize": 2, "authorization": 2,
    "identity": 1, "identity theft": 2, "protect": 1,
    "protect your account": 2, "block": 1, "blocked": 2,
    "verify identity": 2, "confirm identity now": 2, "kyc": 2,
    "complete kyc": 2, "know your customer": 2,
    "customer verification": 2, "support team": 1,
    "verification link": 2, "secure link": 2,
    # URLs / phishing indicators
    "http://": 1, "https://": 1, "www.": 1, ".com/": 1, ".in/": 1,
    ".net/": 1, "bitly.com": 1, "tinyurl.com": 1, "shorten": 1,
    "redirect": 1, "verify link": 2, "login link": 2,
    "reset password": 2, "password reset": 2,
    # Payment / India-specific
    "upi": 2, "upi id": 2, "paytm": 2, "phonepe": 2, "google pay": 2,
    "gpay": 2, "mobicash": 2, "bhim": 2, "payment request": 2,
    "payment link": 2, "pay now": 2, "collect request": 2,
    "account transfer": 2, "bank transfer": 2, "neft": 2, "imps": 2,
    "rtgs": 2, "merchant": 1, "invoice": 1, "bill due": 1, "billing": 1,
    # Social engineering
    "we are from": 1, "this is from": 1, "official message": 1,
    "from bank": 2, "from bank support": 2, "from government": 2,
    "from aadhaar": 2, "from uidai": 2, "from customer support": 1,
    "verify with us": 2, "call from bank": 2, "call from support": 1,
    "urgent call": 1,
    # Multi-lingual common phrases
    "verify otp": 3, "enter otp": 3, "enter code": 3,
    "authentication": 2, "authenticator": 2, "security question": 2,
    "mobile verification": 2, "sso": 1, "login": 2,
    "login to your account": 2, "reset": 2, "reset now": 2,
    "reset your password": 2, "expire": 1, "expired": 1,
    "account blocked": 2, "account locked": 2, "unauthorized": 2,
    "safeguard": 1,
    # Hyphenated phishing patterns
    "verify-account": 2, "account-update": 2, "payment-request": 2,
    "confirm-payment": 2, "secure-link": 2, "security-alert": 2,
    "suspicious-login": 2, "immediate-action": 2, "last-chance": 1,
    "final-warning": 1,

    # ── Hindi (Devanagari) ───────────────────────────────────────────────────
    "ओटीपी": 3, "ओटीपी को": 3, "वन टाइम पासवर्ड": 3, "पासवर्ड": 3,
    "पासवर्ड रीसेट": 2, "पिन": 3, "सीवीवी": 3, "एसएसएन": 3,
    "आधार": 3, "आधार नंबर": 3, "खाता": 2, "बैंक": 2, "बैंक खाता": 2,
    "खाता संख्या": 2, "अपने खाते को सुरक्षित करें": 2,
    "अब सत्यापित करें": 2, "सत्यापित करें": 2, "वेरिफाई": 2,
    "सत्यापन": 1, "सत्यापन लिंक": 2, "एक्सेस": 2, "लेनदेन": 2,
    "भुगतान": 2, "ट्रांसफर": 2, "क्रेडिट": 2, "डेबिट": 2,
    "ट्रांसफर करें": 2, "पे नाउ": 2, "इनाम": 2, "विनर": 2,
    "लॉटरी": 2, "दावा": 2, "रिडीम": 2, "रिडीम करें": 2, "रिफंड": 2,
    "सस्पेंड": 2, "सस्पेंडेड": 2, "पुष्टि": 2, "पुष्टि करें": 2,
    "अलर्ट": 2, "सुरक्षा अलर्ट": 2, "तुरंत": 2, "फौरन": 2,
    "त्वरित कार्रवाई": 2, "तत्काल कार्रवाई": 1, "तत्काल अपडेट": 1,
    "तुरंत अपडेट": 1, "अंतिम नोटिस": 1, "अंतिम मौका": 1,
    "मिस न करें": 1, "स्कैम": 2, "फ्रॉड": 2, "फिशिंग": 2,
    "हैकिंग": 2, "हैक्ड": 2, "हैकर": 2, "मुफ्त": 1, "ऑफर": 1,
    "क्लिक": 1, "यहाँ क्लिक करें": 1, "लिंक": 1,
    "लिंक पर क्लिक करें": 1, "डाउनलोड": 1, "जोखिम": 1,
    "जोखिम-मुक्त": 1, "गारंटी": 1, "ट्रायल": 1, "विशेष": 1,
    "महत्वपूर्ण": 1, "ध्यान दें": 1, "पहचान": 1, "पहचान चोरी": 2,
    "सुरक्षित": 1, "सुरक्षा करें": 1, "सुरक्षा": 1, "सावधानी": 1,
    "चेतावनी": 1, "खतरा": 1, "साझा न करें": 3, "शेयर न करें": 3,
    "संदेहजनक": 1, "नकली": 1, "पैसे": 1, "नकद": 1, "उपहार": 1,
    "बोनस": 1, "सब्सक्राइब": 1, "अभी सब्सक्राइब करें": 1,
    "अभी कॉल करें": 1, "हमें कॉल करें": 1, "ग्राहक सेवा": 1,
    "ग्राहक सहायता": 1, "सहायता डेस्क": 1, "संपर्क करें": 1,
    "हमसे संपर्क करें": 1, "विवरण सत्यापित करें": 2,
    "जानकारी अपडेट करें": 2, "अपनी जानकारी अपडेट करें": 2,
    "विवरण प्रदान करें": 2, "दस्तावेज़ जमा करें": 2,
    "दस्तावेज़ भेजें": 2, "ओटीपी साझा करें": 3,
    "पासवर्ड साझा करें": 3, "पिन साझा करें": 3,
    "संदिग्ध गतिविधि": 1, "संदिग्ध लेनदेन": 2, "अंतिम चेतावनी": 1,
    "सुरक्षा कोड": 3, "प्रमाणीकरण कोड": 3, "प्राधिकरण": 2,
    "पहचान सत्यापित करें": 2, "अब पहचान की पुष्टि करें": 2,
    "केवाईसी": 2, "केवाईसी पूरा करें": 2, "अपने ग्राहक को जानें": 2,
    "ग्राहक सत्यापन": 2, "पासवर्ड रीसेट करें": 2, "पासवर्ड रिसेट": 2,
    "लॉगिन लिंक": 2, "लॉगिन करें": 2, "खाता अपडेट": 2,
    "भुगतान अनुरोध": 2, "भुगतान लिंक": 2, "अब भुगतान करें": 2,
    "संग्रह अनुरोध": 2, "बैंक ट्रांसफर": 2, "मर्चेंट": 1,
    "चालान": 1, "बिल देय": 1, "बिलिंग": 1, "हम बैंक से हैं": 2,
    "हम समर्थन से हैं": 1, "सरकारी संदेश": 2, "आधार से": 2,
    "यूआईडीएआई से": 2, "ग्राहक सहायता से": 1,
    "हमारे साथ सत्यापित करें": 2, "बैंक से कॉल": 2,
    "समर्थन से कॉल": 1, "आपातकालीन कॉल": 1, "ग्राहक सेवा टीम": 1,

    # ── Gujarati ─────────────────────────────────────────────────────────────
    "ઓટિપિ": 3, "ઓટીપી": 3, "પાસવર્ડ": 3, "પાસવર્ડ રીસેટ": 2,
    "પિન": 3, "સિવિવી": 3, "એસએસએન": 3, "આધાર": 3, "ખાતા": 2,
    "બેંક": 2, "બેંક ખાતું": 2, "ખાતા નંબર": 2,
    "તમારા ખાતાને સુરક્ષિત કરો": 2, "હવે વેરિફાઈ કરો": 2,
    "વેરિફાઈ": 2, "સત્યાપન": 1, "સત્યાપન લિંક": 2, "એક્સેસ": 2,
    "ટ્રાન્ઝેક્શન": 2, "પેમેન્ટ": 2, "ટ્રાન્સફર": 2,
    "ક્રેડિટ": 2, "ડેબિટ": 2, "ઇનામ": 2, "વિનર": 2, "લોટરી": 2,
    "દાવો": 2, "રિડિમ": 2, "રિડિમ કરો": 2, "રિફંડ": 2,
    "સસ્પેન્ડ": 2, "પુષ્ટિ": 2, "પુષ્ટિ કરો": 2, "અલર્ટ": 2,
    "સુરક્ષા અલર્ટ": 2, "તાત્કાલિક": 2, "તુરંત": 2,
    "તાત્કાલિક કાર્યવાહી": 2, "તાત્કાલિક અપડેટ": 1,
    "અંતિમ સૂચના": 1, "છેલ્લો મોકો": 1, "મિસ ન કરો": 1,
    "ઠગ": 2, "ફ્રોડ": 2, "ફિશિંગ": 2, "હેકિંગ": 2, "હેક્ડ": 2,
    "હેકર": 2, "મફત": 1, "ફ્રી": 1, "ઓફર": 1, "ક્લિક": 1,
    "અહીં ક્લિક કરો": 1, "લિંક": 1, "લિંક પર ક્લિક કરો": 1,
    "ડાઉનલોડ": 1, "જોખમ": 1, "જોખમ-મુક્ત": 1, "ગેરંટી": 1,
    "ટ્રાયલ": 1, "વિશેષ": 1, "મહત્વપૂર્ણ": 1, "ધ્યાન આપો": 1,
    "ઓળખ": 1, "ઓળખ-ચોરી": 2, "સુરક્ષિત": 1, "સુરક્ષા કરો": 1,
    "શંકાસ્પદ": 1, "ચેતવણી": 1, "સાવચેતી": 1, "પેસા": 1,
    "નકદ": 1, "ઉપહાર": 1, "બોનસ": 1, "સબ્સ્ક્રાઇબ": 1,
    "સાંજે ન કરો": 3, "શેર ન કરો": 3, "સંદેહજનક": 1, "નકલી": 1,
    "અંતિમ ચેતવણી": 1, "સુરક્ષા કોડ": 3, "પ્રમાણિકરણ કોડ": 3,
    "પ્રાધિકરણ": 2, "ઓળખ સત્યાપિત કરો": 2,
    "હવે ઓળખની પુષ્ટિ કરો": 2, "કેવાયસી": 2,
    "કેવાયસી પૂર્ણ કરો": 2, "તમારા ગ્રાહકને જાણો": 2,
    "ગ્રાહક સત્યાપન": 2, "પાસવર્ડ રીસેટ કરો": 2, "લોગિન લિંક": 2,
    "લોગિન કરો": 2, "ખાતા અપડેટ": 2, "ચુકવણી વિનંતી": 2,
    "ચુકવણી લિંક": 2, "હવે ચુકવણી કરો": 2, "સંગ્રહ વિનંતી": 2,
    "બેંક ટ્રાન્સફર": 2, "મર્ચન્ટ": 1, "ચલાન": 1, "બિલ બાકી": 1,
    "બિલિંગ": 1, "અમે બેંકમાંથી છીએ": 2, "અમે સપોર્ટમાંથી છીએ": 1,
    "સરકારી સંદેશો": 2, "આધારથી": 2, "યુઆઈડીએઈથી": 2,
    "ગ્રાહક સહાયતા થી": 1, "અમારા સાથે વેરિફાઈ કરો": 2,
    "બેંકથી કોલ": 2, "સપોર્ટથી કોલ": 1, "તાત્કાલિક કોલ": 1,
    "ગ્રાહક સેવા ટીમ": 1,
}
